# Generated by Django 5.0.4 on 2025-03-19 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_sub'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImages',
            new_name='PostImage',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category'),
        ),
    ]
